Vagrant.configure(2) do |config|
  config.vm.box = 'windows-server-core-1709'

  config.vm.hostname = 'kubelet01'

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.provider 'libvirt' do |lv|
    lv.memory = 6144
    lv.cpus = 2
    lv.keymap = 'pt'
    lv.nested = true
    lv.cpu_mode = "host-model"
    lv.management_network_name = "vagrant-libvirt-k8s"
    lv.management_network_address = "192.168.0.0/16"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 6144
    vb.cpus = 2

    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

end
