Vagrant.configure(2) do |config|
  # config.vm.box = 'windows-server-core-1709-amd64-lv'
  config.vm.box = 'windows-server-core-1709'

  config.vm.hostname = 'kubelet01'

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.provider 'libvirt' do |lv|
    lv.memory = 6144
    lv.cpus = 2
    lv.keymap = 'pt'
    config.vm.synced_folder '.', '/vagrant', disabled: true

  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 6144
    vb.cpus = 2

    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    
    # 26 mins for 45MB!!
    #vb.customize ["modifyvm", :id, "--nictype1", "82545EM"]
  end

end
